spring:
  application:
    name: psp-system-assignment

logging:
  level:
    com.github.dj0l33x.psp: ${MAIN_LOG_LEVEL:DEBUG}
    org.apache: ${APACHE_LOG_LEVEL:WARN}
    org.springframework: ${SPRING_LOG_LEVEL:WARN}